### ISSUE TITLE
crontable

### ISSUE THREAD

**Issue by JayLI2010** [slackhq/python-rtmbot#22]
I can't find any documentation on crontable.append used by one of the plugins (counter.py)....I'd like to use the counter.py to post the time every hour on the hour but I'm not familiar with how to do this using the crontable.

I modified counter.py to use the python scheduler (2.7) but it's not working... for some reason, the rtmbot script doesn't seem to recognize it, I don't get any error but it's not posting the time.   

-----------------------------------------------------------------------------
crontable.append([5,"say_time"])

def say_time():
    #NOTE: you must add a real channel ID for this to work
    outputs.append(["D12345678", time.time()])
-----------------------------------------------------------------------------

Here's my code : 
-----------------------------------------------------------------------------
import schedule
import time
outputs = []

def say_time():
      outputs.append(["D12345678", time.ctime()])

schedule.every(2).minutes.do(say_time)

while True:
	schedule.run_pending()
	time.sleep(1)
------------------------------------------------------------------------------

**Comment by jammons** [comment]
Hi JayLI2010! Sorry this took us so long to get you a response. I just played around with this some and you should be able to get what you want if you do this:

```
import time

crontable = []
crontable.append([1, "say_time"])
outputs = []


def say_time():
    outputs.append(["D0K872B25", time.ctime()])
```

The crontab is a nicety that is built in so you don't have to deal with running the scheduler yourself, you can just use the crontable.append([# of seconds, 'method_name']) convention and it will do that for you.

Note that you will want to name your plugin something other than time.py as this will collide with the time module.

Let me know if you have any other issues.
-Jeff
