### ISSUE TITLE
Bot does not work upon invitiation to new channel or private group

### ISSUE THREAD

**Issue by mac-reid** [slackhq/python-rtmbot#24]
## Description:
After inviting a bot to a channel or private group, the bot does not respond in the channel. After restarting the bot process, the bot correctly responds in the channel/group.

## Date Seen:
07 October 2015

## Bot Version:
The bot I run is based on https://github.com/slackhq/python-rtmbot from 22fb111. I forked the repo here: https://github.com/mac-reid/python-rtmbot

Running on Python 2.7.6 with the following modules (in virtualenv):
backports.ssl-match-hostname (3.4.0.2)
docutils (0.12)
google-api-python-client (1.4.2)
httplib2 (0.9.2)
lockfile (0.10.2)
oauth2client (1.5.1)
pip (7.1.2)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
python-daemon (2.0.6)
PyYAML (3.11)
requests (2.7.0)
rsa (3.2)
setuptools (18.2)
simplejson (3.8.0)
six (1.9.0)
slackclient (0.16)
uritemplate (0.6)
websocket-client (0.32.0)
wheel (0.24.0)

## Severity:
Trivial

## Steps to reproduce:
  1. Make a new channel or private group
  2.  /invite @botname
  3. type message to trigger bot

## Actual Behavior:
Start the bot and connect to slack. The bot shows user presence. Create a new channel/group and invite the bot. Type a message to trigger the bot (such as @botname: help). The bot receives the message but fails to respond on the new channel.

## Expected Behavior:
Start the bot and connect to slack. The bot shows user presence. Create a new channel/group and invite the bot. Type a message to trigger the bot (such as @botname: help). The bot receives the message and responds on the new channel.

## Testing Steps:
When the bot is added to the new channel and receives a message, the output to send is added to the channel, but the rtmbot never actually gets to sending the message on the channel.

## Workaround:
Restart the bot each time it is added to a new channel.

**Comment by farshield** [comment]
Confirmed. This is indeed happening. Anyone has a solution?

**Comment by bscan** [comment]
@jammons, this issue can be closed. The problem was in SlackClient, not rtmbot, and the above commit fixes it.

**Comment by jammons** [comment]
👍
