### ISSUE TITLE
tests!

### ISSUE THREAD

**Issue by magniff** [slackhq/python-rtmbot#27]
Need tests dude, please add some.

**Comment by frankV** [comment]
:+1: I'm down to help with this.

**Comment by jammons** [comment]
There's an example test file now and TravisCI running in this repo. Please add some! :) I'm working on a refactor that will make it easier to test also.

**Comment by jammons** [comment]
Ok, coverage stats are now installed and should publish via Coveralls. I'm going to close this issue for now, but recognize that this project needs a lot more tests.
