### ISSUE TITLE
Short links

### ISSUE THREAD

**Issue by farshield** [slackhq/python-rtmbot#29]
How do I make short links work? Also asked the questions on stackoverflow:
http://stackoverflow.com/questions/33994675/slack-rtm-with-python-rtmbot-making-short-links-work

**Comment by smashedr** [comment]
I would also like to know how to do this.

This is currently not working: <https://www.google.com|google>

**Comment by jchudev** [comment]
Short links are still not working for me either. Making an api call to chat.postMessage as an alternative to getting more complex formatting can be dangerous as well. The plugins will receive messages that the bot outputs and can cause quite a mess.

**Comment by jammons** [comment]
This should be doable now using the Web API as per #57
