### ISSUE TITLE
Add the ability to disable link unfurling

### ISSUE THREAD

**Issue by JemarJones** [slackhq/python-rtmbot#48]
Is there a way for us to send links in our messages without having them unfurl?

**Comment by jammons** [comment]
Hi!

Check out the documentation here for that: https://api.slack.com/docs/message-attachments#unfurling

As of right now, the RTMBot code won't let you configure it to allow passing the `unfurl_links` flag. There are a couple of different ways you could add that code depending on your use case. Or you could use the python-slackclient library to make the call directly and include that flag.

Let me know if you need more guidance beyond the docs. Or file an issue request and I'll try to get to it at some point (might be a while though...)

**Comment by JemarJones** [comment]
@jammons Thanks for the info! 

Correct me if i'm wrong, but from what i can tell the `unfurl_links` flag doesn't seem to be a part of the RTM api? Would i need to switch to the regular API to get this functionality?

**Comment by jammons** [comment]
Yeah, I believe you would have to use a regular API call to do this. The RTM API only supports basic message formatting: https://api.slack.com/docs/message-formatting

**Comment by JemarJones** [comment]
I see. I suppose that implementing message sending via the regular API wouldn't make much sense to fit into an **rtm**bot?

**Comment by jammons** [comment]
Sorry for the slow response. I think I missed the above message.

I'm actually working on adding an easier way to call the Slack Web API from within plugins. Hopefully that will solve a lot of use-cases like this.

**Comment by beastduck** [comment]
I agree with @JemarJones, wouldn't it make more sense if the bot is designed to be more than an RTM bot? Because currently if we allow Web API calls within plugins then it defeats the purpose of an RTM bot.

**Comment by jammons** [comment]
@beastduck how would you describe the purpose of an RTM bot?

In my mind, allowing the possibility of making direct Web API calls from within the plugins, but still also making it simple to continue to use the RTM would be a feature upgrade with no real downside.

It's possible I'm missing something in this line of thinking though, so I'd be curious to hear your thoughts.

**Comment by beastduck** [comment]
@jammons I was being consistent with respect to its name and its implementation. RTM bot can immediately tell one that its exclusively using the RTM api. It could've been more intuitive if it was called like slack bot? 

Function-wise it will be wise to allow the Web API of course because the RTM api is just lacking some features. 

cheers

**Comment by jammons** [comment]
Ok, this should be doable using the Web API within plugins for now. Thanks to #57
