### ISSUE TITLE
Add the ability to add message attachments

### ISSUE THREAD

**Issue by nadavoosh** [slackhq/python-rtmbot#49]
Does this plugin framework allow the RTM bot to send messages with attachments?

**Comment by jammons** [comment]
It does not at the moment, unfortunately. I'll leave this request open though as a feature request. (If you'd like to help out with a PR, let me know!)

**Comment by nadavoosh** [comment]
@jammons I would be excited to help out! Are there contribution guidelines anywhere?

**Comment by tthayer** [comment]
From Slack's official documentation, it doesn't appear that attachments are supported by the RTM method:

"Using the Real Time Messaging API
To send messages on behalf of the user owning a specific token, post message JSON directly into an open websocket connection in the Real Time Messaging API.

You cannot provide attachments nor buttons to messages posted over the RTM API. If your bot user needs to send more complex messages, use the web API's chat.postMessage."
https://api.slack.com/docs/messages

**Comment by jammons** [comment]
@nadavoosh I'm working on getting some into this repo. Hopefully I can track that down in the next week or so.

I think that tthayer is correct here. We're working on getting the SlackClient instance into the plugin scope which will let you make calls to the web API from within a plugin manually. This will probably be in the next few weeks. If you have some thoughts on an approach and want me to give them a look, please submit a PR or just reply here.

**Comment by jammons** [comment]
Ok, this should be working now thanks to PR #57
