### ISSUE TITLE
Cannot listen to message events in channels

### ISSUE THREAD

**Issue by codehive** [slackhq/python-rtmbot#5]
Hi, 

I have a channel #test in my slack account. While rtmbot is running, even if message some text to #test, rtmbot does not show that as a event. It reports if the message is starred/ unstarred. 

To further investigate, I opened a web socket and tried seeing if I am receiving any data when I post to #test, but I dont get that. 

Can you tell me if there is any thing that I can look into ?

**Comment by ChihChengLiang** [comment]
Make sure you use 'id' of the channel.

**Comment by hlprimm** [comment]
I also had this issue: you have to add the bot to the channel or else it won't see anything.

**Comment by jammons** [comment]
Hopefully one of the above comments points you in the right direction. If not, please re-open this thread and we'll see if we can fix it. Thanks!
