### ISSUE TITLE
interaction with OH rules?

### ISSUE THREAD

**Issue by jbarneson** [slackhq/python-rtmbot#61]
would it be possible to have rtmbot interact with OH rules to post content out to slack based on triggers in OH instead of requests from slack users?

ie -- I'd like to create a rule to post perimeter security exceptions (doors/windows opening and motion) to slack. Other irregular events such as thermostat temp/mode changes, presence, usage stats, and alarms would all be nice to post in my family slack stream

**Comment by jammons** [comment]
That sounds like a cool idea. If you don't need the ability to respond to users and just want to create a broadcast service, check out this library: https://github.com/slackhq/python-slackclient

That one will let you make arbitrary calls to the Slack Web API using whatever Python code you'd like.
