### ISSUE TITLE
Is there an option to read values from rtmbot.conf in plugins?

### ISSUE THREAD

**Issue by omerxx** [slackhq/python-rtmbot#67]
Are plugins aware in any way to the parameters from the conf file?

I'd like to add parameters such as 'bot_name' to use later on in my plugins.
I can do this on my own and create a PR, but don't want to do a duplicate job.

**Comment by rplatel** [comment]
There's an option to pass "plugin_config" to the plugin's __init__:

`class OhHeyPlugin(Plugin):

  def __init__(self, name=None, slack_client=None, plugin_config=None):
    super(OhHeyPlugin, self).__init__(name, slack_client, plugin_config)
    print json.dumps(plugin_config)`

Then in rtmbot.conf
`#DEBUG: True # make this False in production
DEBUG: False # ok
SLACK_TOKEN: "xoxb-xxxxxxxxxxxxxxxxxxxxxxx"
ACTIVE_PLUGINS:
    - plugins.ohhey.OhHeyPlugin
OhHeyPlugin:
    name : Bob Bobber
    things :
      - item1
      - item2
      - item3`

Gives:
`rtmbot
{"things": ["item1", "item2", "item3"], "name": "Bob Bobber"}`

**Comment by omerxx** [comment]
Thanks!
