### ISSUE TITLE
Feature request - Access get_slack_client() in filters

### ISSUE THREAD

**Issue by jyap808** [slackhq/python-rtmbot#8]
Feature request to access get_slack_client() in filters... So we can interact with the Slack API in filters.

Thanks.

**Comment by aerickson** [comment]
Big +1 on this.

**Comment by frankV** [comment]
:+1:

**Comment by jammons** [comment]
By filters do you mean plugins?

**Comment by jyap808** [comment]
I totally forget. Closing this since I moved to a Go library. Someone can feel free to open a new Ticket and reference this.

**Comment by jammons** [comment]
Cool, thanks for the response. Sorry we've taken so long to get around to this.
